In [1]:
import pandas as pd 
import numpy as np 
import scipy 
import statsmodels.api as sm 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df = pd.read_csv('../data/sample.csv') 
df.head()

   col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9

In [3]:
import sys
from datetime import date
sys.path.append('../src')
from data_utils import load_ohlcv, check_missing_prices, check_missing_volumes, check_duplicates, check_invalid_dates, check_zero_prices, check_extreme_returns, check_volume_spikes

df = load_ohlcv(["AAPL", "MSFT"], start="2021-01-01", end=str(date.today()))
df.head()
print(df['date'].min(), df['date'].max())
print(df['ticker'].unique())
print(df['date'].nunique(), "trading days")

df.to_csv('../data/sample_ohlcv.csv', index=False)

2021-01-04 00:00:00 2026-09-22 00:00:00
<StringArray>
['AAPL', 'MSFT']
Length: 2, dtype: str
1436 trading days

In [4]:
tickers = [
    "NVDA", "META", "GOOGL", "MSFT", "TSLA", "ORCL", "AMD", "INTC", "SMCI", "MU",
    "RKLB", "WDC", "STX", "CRWD", "PLTR",
    "AAPL", "AMZN", "AVGO", "CSCO", "ADBE", "CRM", "NFLX", "QCOM", "TXN", "TSM",
    "JPM", "BAC", "WFC", "V", "MA",
    "JNJ", "PFE", "MRK", "UNH", "ABT",
    "PG", "KO", "PEP", "WMT", "COST",
    "HD", "NKE", "MCD", "ASML",
    "XOM", "CVX",
    "HON", "CAT", "GE",
    "TMO"
]
df = load_ohlcv(tickers, start="2021-01-01", end=str(date.today()))

In [5]:
missing_prices = check_missing_prices(df)
missing_volumes = check_missing_volumes(df)
duplicates = check_duplicates(df)
invalid_dates = check_invalid_dates(df, start="2021-01-01", end=str(date.today()))
zero_prices = check_zero_prices(df)
extreme_returns = check_extreme_returns(df)
volume_spikes = check_volume_spikes(df)

print("Missing prices:", len(missing_prices))
print("Missing volumes:", len(missing_volumes))
print("Duplicates:", len(duplicates))
print("Invalid dates:", len(invalid_dates))
print("Zero prices:", len(zero_prices))
print("Extreme returns (>50%):", len(extreme_returns))
print("Volume spikes:", len(volume_spikes))

Missing prices: 50
Missing volumes: 0
Duplicates: 0
Invalid dates: 0
Zero prices: 0
Extreme returns (>50%): 0
Volume spikes: 29

In [6]:
missing_prices[['date','ticker']]

Price       date ticker
1435  2026-09-22   NVDA
2871  2026-09-22   META
4307  2026-09-22  GOOGL
5743  2026-09-22   MSFT
7179  2026-09-22   TSLA
8615  2026-09-22   ORCL
10051 2026-09-22    AMD
11487 2026-09-22   INTC
12923 2026-09-22   SMCI
14359 2026-09-22     MU
15795 2026-09-22   RKLB
17231 2026-09-22    WDC
18667 2026-09-22    STX
20103 2026-09-22   CRWD
21539 2026-09-22   PLTR
22975 2026-09-22   AAPL
24411 2026-09-22   AMZN
25847 2026-09-22   AVGO
27283 2026-09-22   CSCO
28719 2026-09-22   ADBE
30155 2026-09-22    CRM
31591 2026-09-22   NFLX
33027 2026-09-22   QCOM
34463 2026-09-22    TXN
35899 2026-09-22    TSM
37335 2026-09-22    JPM
38771 2026-09-22    BAC
40207 2026-09-22    WFC
41643 2026-09-22      V
43079 2026-09-22     MA
44515 2026-09-22    JNJ
45951 2026-09-22    PFE
47387 2026-09-22    MRK
48823 2026-09-22    UNH
50259 2026-09-22    ABT
51695 2026-09-22     PG
53131 2026-09-22     KO
54567 2026-09-22    PEP
56003 2026-09-22    WMT
57439 2026-09-22   COST
58875 2026-09-22     HD
60311 2026-09-22    NKE
61747 2026-09-22    MCD
63183 2026-09-22   ASML
64619 2026-09-22    XOM
66055 2026-09-22    CVX
67491 2026-09-22    HON
68927 2026-09-22    CAT
70363 2026-09-22     GE
71799 2026-09-22    TMO

In [7]:
volume_spikes['ticker'].value_counts()

ticker
JNJ     8
RKLB    4
CRWD    3
QCOM    2
META    1
MSFT    1
NFLX    1
PFE     1
MRK     1
UNH     1
ABT     1
PG      1
WMT     1
MCD     1
CVX     1
HON     1
Name: count, dtype: int64

In [8]:
volume_spikes[['date','ticker','volume']].sort_values('volume', ascending=False).head(15)

Price       date ticker      volume
30482 2022-04-20   NFLX  1333875000
55833 2026-01-16    WMT   415144600
45574 2025-03-21    PFE   349996500
1894  2022-10-27   META   232316600
19539 2024-06-21   CRWD   209024000
19559 2024-07-22   CRWD   198270000
5683  2026-06-26   MSFT   186201600
19558 2024-07-19   CRWD   168582800
43741 2023-08-21    JNJ   151319500
48484 2025-05-15    UNH   121849200
43743 2023-08-23    JNJ   119011400
46140 2021-10-01    MRK   102497300
43737 2023-08-15    JNJ    88958100
43738 2023-08-16    JNJ    85832700
32801 2025-10-27   QCOM    81799300

In [9]:
df['adj_factor'] = df['close'] / df['adj_close']